share_shopping/share_shopping/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
    path('main/', include('shopping_list.urls'))
]

share_shopping/shopping_list/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('add/<shopping_list_id>', views.add_item, name='add'),
    path('bought/<item_id>/<shopping_list_id>', views.bought_item, name='bought'),
    path('not-bought/<item_id>/<shopping_list_id>', views.not_bought_item, name='not-bought'),
    path('delete-item/<item_id>/<shopping_list_id>', views.delete_item, name='delete-item'),
    path('create-list/', views.create_list, name='create-list'),
    path('shopping-lists/<shopping_list_id>', views.shopping_list_details, name='detail'),
    path('delete-list/<shopping_list_id>', views.delete_shopping_list, name='delete-shopping-list'),
    path('share-list/<shopping_list_id>', views.share_shopping_list, name='share-shopping-list'),
    path('remove-user-from-list/<shopping_list_id>/<username>', views.remove_user_from_shopping_list, name='remove-user-from-shopping-list'),
    path('change-owner-of-list/<shopping_list_id>/<username>', views.change_owner_of_shopping_list, name='change-owner'),
    path('make-admin/<shopping_list_id>/<username>', views.make_user_admin_of_shopping_list, name='make-admin'),
    path('add-comment/<shopping_list_id>', views.add_comment, name='add-comment'),
    path('delete-comment/<shopping_list_id>/<comment_id>', views.delete_comment, name='delete-comment'),
    path('reply/<shopping_list_id>/<comment_id>', views.reply, name='reply'),
    path('delete-reply/<shopping_list_id>/<reply_id>', views.delete_reply, name='delete-reply')
]

share_shopping/user/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views



app_name = "user"

urlpatterns = [
	path('register/', views.register, name="register"),
	path('registered/', views.registered, name="registered"),
	path('', views.login_request, name="login"),
	path('logout/', views.logout_request, name="logout"),
]

share_shopping/shopping_list/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.


User = get_user_model()
default_shopping_list_ID = 1


class ShoppingList(models.Model):
    title = models.CharField(max_length=25)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1, related_name='owner')
    participants = models.ManyToManyField(User, related_name='participants')
    admins = models.ManyToManyField(User, related_name='admins')

    def __str__(self):
        return self.title

    # Return the user's shopping lists
    @staticmethod
    def get_user_shopping_lists(user):
        owned_shopping_lists = ShoppingList.objects.filter(owner=user)
        other_shopping_lists = ShoppingList.objects.filter(participants=user)
        other2_shopping_lists = ShoppingList.objects.filter(admins=user)
        my_shopping_lists = other_shopping_lists | owned_shopping_lists | other2_shopping_lists
        return my_shopping_lists.distinct().order_by('id')

    # Check if user is a member of shopping list
    def user_is_member(self, user):
        return user == self.owner or user in self.participants.all() or user in self.admins.all()

    # Check if user has admin rights
    def user_has_admin_rights(self, user):
        return user in self.admins.all() or user == self.owner


class Item(models.Model):
    name = models.CharField(max_length=80)
    amount = models.CharField(max_length=20)
    bought = models.BooleanField(default=False)
    shopping_list = models.ForeignKey(ShoppingList, on_delete=models.CASCADE, default=default_shopping_list_ID)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, default=1, null=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=150)
    shopping_list = models.ForeignKey(ShoppingList, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.author) + " : " + self.date.strftime('%Y-%m-%d %H:%M')

    def replies(self):
        return Reply.objects.filter(parent_comment=self)


class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=150)
    parent_comment = models.ForeignKey(Comment, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return str(self.author) + " : " + self.date.strftime('%Y-%m-%d %H:%M')

share_shopping/shopping_list/forms.py
from django import forms
from django.contrib.auth import get_user_model
User = get_user_model()

class ItemForm(forms.Form):
    name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter name of item',
            }
        )
    )
    amount = forms.CharField(
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter amount of item',
            }
        )
    )


class ShoppingListForm(forms.Form):
    title = forms.CharField(
        max_length=13,
        widget=forms.TextInput(
            attrs={
                'color': 'red',
                'placeholder': 'Enter title of new list'
            }
        )
    )


class ShareForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter username'
            }
        )
    )

    def clean_username(self, *args, **kwargs):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).count() == 0:
            raise forms.ValidationError('User does not exist. Please enter the username of an existing user.')
        return username


class CommentForm(forms.Form):
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder':'Write your comment here'
            }
        ),
        max_length=150)


class ReplyForm(forms.Form):
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder':'Write your reply here'
            }
        ),
        max_length=150)

share_shopping/shopping_list/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.contrib import messages

from .models import Item, ShoppingList, Comment, Reply
from .forms import ItemForm, ShoppingListForm, ShareForm, CommentForm, ReplyForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from user import views, urls

# Create your views here.
User = get_user_model()
app_name = "shopping_list"


# Redirect the user to the main site
@login_required(login_url='')
def index(request):
    my_shopping_lists = ShoppingList.get_user_shopping_lists(request.user)
    shopping_list_form = ShoppingListForm()

    context = {
        'shopping_list_form': shopping_list_form,
        'my_shopping_lists': my_shopping_lists,          # List of shopping lists the user owns/participates in
    }

    return render(request, 'shopping_list/index.html', context)


# Redirect the user to look at the shopping list details
@login_required(login_url='')
def shopping_list_details(request, shopping_list_id):
    error_message = 'Could not view the shopping list.'
    user = request.user
    try:
        shopping_list = ShoppingList.objects.get(pk=shopping_list_id)
    except ShoppingList.DoesNotExist:
        messages.error(request, 'The shopping list has either been deleted or you might not have permission to view it. ' + error_message)
        return redirect('index')

    if not shopping_list.user_is_member(request.user):
        messages.error(request, 'You are not a member of the shopping list. ' + error_message)
        return redirect('index')

    my_shopping_lists = ShoppingList.get_user_shopping_lists(user)
    shopping_list_form = ShoppingListForm()
    item_list = Item.objects.filter(shopping_list=shopping_list_id)
    comments = Comment.objects.filter(shopping_list=shopping_list).order_by("date")
    comment_form = CommentForm()
    reply_form = ReplyForm()

    context = {
        'shopping_list': shopping_list,             # ShoppingList which is being inspected by user
        'shopping_list_form': shopping_list_form,
        'item_list': item_list,                     # List of Item objects in the inspected ShoppingList
        'item_form': ItemForm(),
        'comments': comments,
        'share_form': ShareForm(),
        'my_shopping_lists': my_shopping_lists,
        'comment_form': comment_form,
        'reply_form': reply_form
    }

    return render(request, 'shopping_list/shopping_list.html', context)


# Add item to a shopping list
@login_required(login_url='')
@require_POST
def add_item(request, shopping_list_id):
    error_message = 'Could not add item to the shopping list.'
    try:
        shopping_list = ShoppingList.objects.filter(pk=shopping_list_id)[0]
    except ShoppingList.DoesNotExist:
        messages.error(request, 'The shopping list has been deleted. ' + error_message)
        return redirect('index')

    creator = request.user

    if not shopping_list.user_is_member(request.user):
        messages.error(request, 'You are not a member of the shopping list. ' + error_message)
        return redirect('index')

    form = ItemForm(request.POST)
    if form.is_valid():
        new_item = Item(
            name=request.POST['name'],
            amount=request.POST['amount'],
            shopping_list=shopping_list,
            creator=creator
        )
        new_item.save()
        return redirect('detail', shopping_list_id)
    else:
        return redirect('index')


# Mark an item as bought
@login_required(login_url='')
def bought_item(request, item_id, shopping_list_id):
    error_message = 'Could not mark item as bought.'
    try:
        shopping_list = ShoppingList.objects.filter(pk=shopping_list_id)[0]
    except ShoppingList.DoesNotExist:
        messages.error(request, 'The shopping list has been deleted. ' + error_message)
        return redirect('index')

    if not shopping_list.user_is_member(request.user):
        messages.error(request, 'You are not a member of the shopping list. ' + error_message)
        return redirect('index')

    try:
        item = Item.objects.get(pk=item_id)
        item.bought = True
        item.save()
    except Item.DoesNotExist:
        messages.error(request, 'The item has been deleted. ' + error_message)
    finally:
        return redirect('detail', shopping_list_id)


# Unmark an item as bought
@login_required(login_url='')
def not_bought_item(request, item_id, shopping_list_id):
    error_message = 'Could not mark item as not bought.'
    try:
        shopping_list = ShoppingList.objects.filter(pk=shopping_list_id)[0]
    except ShoppingList.DoesNotExist:
        messages.error(request, 'The shopping list has been deleted. ' + error_message)
        return redirect('index')

    if not shopping_list.user_is_member(request.user):
        messages.error(request, 'You are not a member of the shopping list. ' + error_message)
        return redirect('index')

    try:
        item = Item.objects.get(pk=item_id)
        item.bought = False
        item.save()
    except Item.DoesNotExist:
        messages.error(request, 'The item has been deleted. ' + error_message)
    finally:
        return redirect('detail', shopping_list_id)


# Delete an item of a shopping list
@login_required(login_url='')
@require_POST
def delete_item(request, item_id, shopping_list_id):
    error_message = 'Could not delete item.'
    try:
        shopping_list = ShoppingList.objects.filter(pk=shopping_list_id)[0]
    except ShoppingList.DoesNotExist:
        messages.error(request, 'The shopping list has been deleted. ' + error_message)
        return redirect('index')

    if not shopping_list.user_is_member(request.user):
        messages.error(request, 'You are not a member of the shopping list. ' + error_message)
        return redirect('index')

    try:
        item = Item.objects.get(pk=item_id)
    except Item.DoesNotExist:
        return redirect('detail', shopping_list_id)

    if not shopping_list.user_has_admin_rights(request.user) and request.user != item.creator:
        messages.error(request, 'You do not have permission to delete the item. ' + error_message)
        return redirect('detail', shopping_list_id)

    item.delete()
    return redirect('detail', shopping_list_id)


# Create a shopping list and get redirected to see it as your view
@login_required(login_url='')
@require_POST
def create_list(request):
    shopping_list_form = ShoppingListForm(request.POST)
    owner = request.user

    if shopping_list_form.is_valid():
        new_shopping_list = ShoppingList(
            title=request.POST['title'],
            owner=owner
        )
        new_shopping_list.save()
        return redirect('detail', new_shopping_list.id)
    else:
        messages.error(request, "Something went wrong with creation of shopping list. Please try again.")
        return redirect('index')


# Delete a shopping list
@login_required(login_url='')
def delete_shopping_list(request, shopping_list_id):
    error_message = 'Could not delete the shopping list.'
    try:
        shopping_list = ShoppingList.objects.filter(pk=shopping_list_id)[0]
        if request.user == shopping_list.owner:
            shopping_list.delete()
            messages.success(request, "Successfully deleted the shopping list!")
        else:
            messages.error(request, 'You are not the owner of the shopping list. ' + error_message)
    finally:
        return redirect('index')


# Add another user to the shopping list as a participator
@login_required(login_url='')
@require_POST
def share_shopping_list(request, shopping_list_id):
    error_message = 'Could not share the shopping list.'
    try:
        shopping_list = ShoppingList.objects.filter(pk=shopping_list_id)[0]
    except ShoppingList.DoesNotExist:
        messages.error(request, 'The shopping list has been deleted. ' + error_message)
        return redirect('index')
    share_form = ShareForm(request.POST)

    if not shopping_list.user_is_member(request.user):
        messages.error(request, 'You are not a member of the shopping list. ' + error_message)
        return redirect('index')

    if share_form.is_valid():
        shared_with_user = User.objects.get(username=request.POST['username'])
        if not shopping_list.user_is_member(shared_with_user):
            shopping_list.participants.add(shared_with_user)
    else:
        messages.error(request, "User does not exist. Please share with an existing user.")
    return redirect('detail', shopping_list_id)


# Remove another user from the shopping list
@login_required(login_url='')
def remove_user_from_shopping_list(request, shopping_list_id, username):
    current_user = request.user
    error_message = 'Could not remove user from shopping list.'
    try:
        shopping_list = ShoppingList.objects.filter(pk=shopping_list_id)[0]
        user_to_be_removed = User.objects.get(username=username)
    except ShoppingList.DoesNotExist:
        messages.error(request, 'The shopping list has been deleted. ')
        return redirect('index')
    except User.DoesNotExist:
        return HttpResponse('Error 400: Bad request.', status=400)

    if not shopping_list.user_is_member(request.user):
        messages.error(request, "You are not a member of the shopping list. " + error_message)
        return redirect('index')

    if not shopping_list.user_has_admin_rights(current_user) and current_user != user_to_be_removed:
        messages.error(request, 'You are do not have admin rights. ' + error_message)
        return redirect('detail', shopping_list_id)

    try:
        if user_to_be_removed in shopping_list.participants.all():
            shopping_list.participants.remove(user_to_be_removed)
        elif user_to_be_removed in shopping_list.admins.all():
            if current_user != shopping_list.owner and current_user != user_to_be_removed:

share_shopping/shopping_list/templates/shopping_list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Shopping list website</title>
    <style>
        a {
            color: black;
            text-decoration: none;
        }
        .item-bought {
	        text-decoration: line-through;
            -webkit-text-fill-color: darkgray;
            color: darkgrey;
        }
        .button-fix {
            float: right;
            margin-top: -7px;
            margin-bottom: -7px;
        }

        /* The Modal (background) */
        .modal {
              display: none; /* Hidden by default */
              position: fixed; /* Stay in place */
              z-index: 1; /* Sit on top */
              top: 15%;

        }
        /* Modal Content/Box */
        .modal-content {
            margin: 2% auto; /* 15% from the top and centered */
            width: fit-content; /* Could be more or less, depending on screen size */
            padding: 10%;
        }

         /* Delete list warning -   modal*/
        .modal-admin {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            top: 15%;
            left: 30%;
            width: 45%;
            background-color: white;

        }

        /* delete list warning - content-box */
        .modal-admin-content {
            margin: 2% auto;
            padding: 3% 10% 3% 10%;
        }

        #id_title{
            color: lightgrey;
        }

    </style>
     <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Simple scrollbar -->
    <link rel="stylesheet" href="https://unpkg.com/simplebar@latest/dist/simplebar.css" />
    <!-- Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<body>
<div class="z-depth-2">
<ul id="dropdown1" class="dropdown-content">
  <li><a href="{% url 'user:logout' %}">Sign out</a></li>
</ul>

<!-- NAVBAR FOR BIG SCREENS -->
<nav class="nav-extended blue-grey darken-4">
    <div class="nav-wrapper">
        <div class="container">
            <a href="#" class="brand-logo">ShareShopping</a>
            <a href="#" class="sidenav-trigger" data-target="mobile-links">
                <i class="material-icons">menu</i>
            </a>
                <a class="right hide-on-small-only dropdown-trigger" href="#" data-target="dropdown1">{{ user.username }}<i class="material-icons right">arrow_drop_down</i></a>
                <a class="right hide-on-med-and-up dropdown-trigger" href="#" data-target="dropdown1"><i class="material-icons right">arrow_drop_down</i></a>
        </div>
    </div>
</nav>
    <div class="col s12 blue-grey darken-4 hide-on-med-and-down" style="height:54px;">
        <ul data-simplebar class="tabs blue-grey darken-4">
            {% for shopping_list in my_shopping_lists %}
            <li class="tab"><a href="{% url 'detail' shopping_list.id %}" style="color: lightgrey;">{{ shopping_list.title }}</a></li>
            {% endfor %}
            <li class="tab">
                <a>
                <form action="{% url 'create-list' %}" method='POST' style="margin-top: -15px; margin-bottom: -15px; overflow-x: hidden;">
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col s12">{{ shopping_list_form.title }}</div>
                    </div>
                </form>
                </a>
            </li>
        </ul>
    </div>
</div>

<!-- NAVBAR FOR SMALL SCREENS/MOBILE -->
<ul class="sidenav" id="mobile-links">
    <li class="row"><h5 class="col s10 offset-s2">My shopping lists</h5></li>
    {% for shopping_list in my_shopping_lists %}
    <li><a href="{% url 'detail' shopping_list.id %}" target="_self">{{ shopping_list.title }}</a></li>
    {% endfor %}
    <li>
    <form action="{% url 'create-list' %}" method='POST'>
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s9">{{ shopping_list_form.title }}</div>
            <div class="input-field col s1">
                <button type='submit' class="waves-effect waves-light btn">
                    <i class="material-icons">add</i>
                </button>
            </div>
        </div>
    </form>
    </li>
    <!-- To make sidenav scrolling function better -->
    <li><div class="row"></div></li>
    <li><div class="row"></div></li>
</ul>
<!-- Error messages -->
{% if messages %}
    <div class="container">
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="card-panel green lighten-3">
                {{message}}
                </div>
            {% else %}
                <div class="card-panel red lighten-3">
                {{message}}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
<!-- The shopping list the user is currently looking at-->
{% block content %}
{% endblock %}

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    $(document).ready(function(){
        $(".toggle-item").hide();
        $('.sidenav').sidenav();
        $(".dropdown-trigger").dropdown();
        $('.collapsible').collapsible();
        $(".toggle-visibility").click(function(){
            $(".toggle-item").toggle();
        });
        $('.tabs').tabs({
            onShow: function (event, ui) {
                formID = $('ul.tabs li a.active').html();
            },
            swipeable: True
        });
    });
</script>
<script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>
</body>
</html>